apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # Using a stable placeholder which will be updated by Jenkins
        image: pratham30/backend:v3 
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://admin:password@mongo:27017/admin"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: three-tier-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
