apiVersion: v1
kind: Namespace
metadata:
  name: three-tier-app
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: three-tier-quota
  namespace: three-tier-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 8Gi
