apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: three-tier-app
type: Opaque
stringData:
  mongo-user: "admin"
  mongo-password: "password"
  mongo-uri: "mongodb://admin:password@mongo:27017/admin"
