apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: three-tier-app
type: Opaque
stringData:
  mongo-user: admin
  mongo-password: change-me
  mongo-uri: mongodb://admin:change-me@mongo:27017/admin
  mongo-keyfile: replace-with-a-long-random-string
